function dibujar_con_camara(C, R, P, X, xin)
  % caras -> Cada fila indica los puntos que forman una cara.
  caras = [...
      1 2 3 4;
      1 5 6 2;
      2 6 7 3;
      3 7 8 4;
      4 8 5 1;
      5 6 7 8 ];

  fig1=figure;
  axis([-10,10,-10,10,-10,10]);
  axis('equal');
  axis('off');
  title('Mundo (X=rojo,Y=verde,Z=azul)');
  hold on;

  % Se dibujan los ejes del mundo.
  line([0 ; 10],...
       [0 ; 0],...
       [0 ; 0],...
       'Color','r');
  text(11, 0, 0, 'X');
  line([0 ; 0],...
       [0 ; 10],...
       [0 ; 0],...
       'Color','g');
  text(0, 11, 0, 'Y');
  line([0 ; 0],...
       [0 ; 0],...
       [0 ; 10],...
       'Color','b');
  text(0, 0, 11, 'Z');     

  % Matriz de colores RGB para cada punto del cubo.
   colores = [...
      0 0 0;...
      0 0 1;...
      0 1 0;...
      0 1 1;...
      1 0 0;...
      1 0 1;...
      1 1 0;...
      1 1 1];

  % Se dibuja el cubo:
  patch('Vertices',[X(1,:);X(2,:);X(3,:)]', ...
        'Faces',caras, 'FaceVertexCData',colores,'FaceColor','flat');

  % Se dibujan los ejes de la camara.
  scatter3(C(1,:),C(2,:),C(3,:),'filled','k');
  Rl = [R(:,1)+C R(:,2)+C R(:,3)+C];
  line([C(1,1) ; Rl(1,1)],...
       [C(2,1) ; Rl(2,1)],...
       [C(3,1) ; Rl(3,1)],...
       'Color','r');
  text(Rl(1,1), Rl(2,1), Rl(3,1), 'X');     
  line([C(1,1) ; Rl(1,2)],...
       [C(2,1) ; Rl(2,2)],...
       [C(3,1) ; Rl(3,2)],...
       'Color','g');
  text(Rl(1,2), Rl(2,2), Rl(3,2), 'Y');          
  line([C(1,1) ; Rl(1,3)],...
       [C(2,1) ; Rl(2,3)],...
       [C(3,1) ; Rl(3,3)],...
       'Color','b');
  text(Rl(1,3), Rl(2,3), Rl(3,3), 'Z');               

  % Se dibuja la imagen vista por la camara:
  fig2 = figure;
  axis('equal');
  axis('off');
  title('Vista de la camara (X=rojo,Y=verde)');
  hold on;

  % Se dibujan los ejes x,y de la camara en la imagen obtenida.
  line([0 ; 1],...
       [0 ; 0],...
       'Color','r');
  text(1.1, 0, 'X');                    
  line([0 ; 0],...
       [0 ; -1],...
       'Color','g');
  text(0, -1.1, 'Y');                         

  patch('Vertices',[xin(1,:);xin(2,:)*-1]', ...
        'Faces',caras, 'FaceVertexCData',colores,'FaceColor','flat');

  
end

      